version: '3.8'

services:
  mysql-db:
    image: mysql:8.0

    container_name: alurafake-db

    restart: always

    environment:
      MYSQL_DATABASE: alurafake
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"

    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data: